language: php

dist: xenial

git:
  quiet: true

cache:
  directories:
    - $HOME/.composer
    - vendor

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

install:
  - composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
